version: 2
jobs:
  unit_tests:
    name: Run nyuki Python test suites
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install -U .
      - run: pip install -r requirements_test.txt
      - run: nosetests --with-xunit --xunit-file=$CIRCLE_TEST_REPORTS/xunit.xml --cover-branches --with-coverage --cover-erase --cover-package=nyuki --cover-html --cover-html-dir=$CIRCLE_ARTIFACTS/coverage

workflows:
  version: 2
  test:
    jobs:
      - unit_tests:
          filters:
            tags:
              only: /.*/
